# services/pdf_report.py
"""
Professional PDF report generator for Aegis security audits.
Uses fpdf2 for lightweight, dependency-free PDF generation.
"""
import io
import os
import html
from datetime import datetime, timezone
from fpdf import FPDF


class AegisPDFReport(FPDF):
    """Custom PDF report with Aegis branding."""

    def __init__(self):
        super().__init__('P', 'mm', 'A4')
        # Use built-in Helvetica; TrueType fonts like DejaVu can be added for Unicode
        self.set_auto_page_break(True, 15)
        self._in_title = False

    def header(self):
        """Aegis branded header on every page."""
        if self.page_no() == 1:
            # Title page header
            self.set_font('Helvetica', 'B', 22)
            self.set_text_color(30, 64, 175)   # deep blue
            self.cell(0, 12, 'AEGIS', align='C', new_x="LMARGIN", new_y="NEXT")
            self.set_font('Helvetica', '', 12)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, 'Security Audit Report', align='C', new_x="LMARGIN", new_y="NEXT")
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.ln(6)
        else:
            # Continuation page header
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 5, 'Aegis Security Audit Report (continued)', align='R', new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

    def footer(self):
        """Footer with page number and generation info."""
        self.set_y(-20)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by Aegis Security Bot | aegis.app', align='C')

    def write_section_title(self, title: str):
        """Write a bold section title."""
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(30, 64, 175)
        self.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(30, 64, 175)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def write_body(self, text: str):
        """Write body text."""
        self.set_font('Helvetica', '', 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 5.5, str(text), align='L')
        self.ln(2)

    def write_key_value(self, key: str, value: str):
        """Write a key-value line with bold key."""
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(30, 64, 175)
        self.cell(50, 6, f'{key}:', align='R')
        self.set_font('Helvetica', '', 10)
        self.set_text_color(50, 50, 50)
        self.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")

    def write_risk_bar(self, score: float):
        """Draw a visual risk score bar."""
        self.set_font('Helvetica', 'B', 28)
        if score >= 7:
            self.set_text_color(220, 38, 38)
        elif score >= 4:
            self.set_text_color(234, 179, 8)
        else:
            self.set_text_color(22, 163, 74)
        self.cell(0, 15, f'{score:.1f} / 10', align='C', new_x="LMARGIN", new_y="NEXT")
        # Visual bar
        bar_width = 140
        bar_height = 8
        x_start = (self.w - bar_width) / 2
        y = self.get_y() + 2
        # Background
        self.set_fill_color(230, 230, 230)
        self.set_draw_color(200, 200, 200)
        self.rect(x_start, y, bar_width, bar_height, style='DF')
        # Filled portion
        filled = int(bar_width * score / 10)
        if score >= 7:
            self.set_fill_color(220, 38, 38)
        elif score >= 4:
            self.set_fill_color(234, 179, 8)
        else:
            self.set_fill_color(22, 163, 74)
        self.rect(x_start, y, filled, bar_height, style='F')
        self.ln(14)

    def write_findings_table(self, findings: list, title: str = "FINDINGS"):
        """Write a styled table of findings."""
        if not findings:
            return
        self.write_section_title(title)
        # Table header
        col_widths = [30, 70, 80]   # Severity, Title, Description
        self.set_fill_color(30, 64, 175)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 9)
        for i, header in enumerate(['Severity', 'Title', 'Description']):
            self.cell(col_widths[i], 7, header, border=1, fill=True, align='C')
        self.ln()
        # Table rows
        row_fill = False
        for f in findings[:15]:   # limit to 15 findings per page
            severity = str(f.get('severity', 'INFO'))
            if severity == 'CRITICAL':
                self.set_text_color(220, 38, 38)
            elif severity == 'HIGH':
                self.set_text_color(200, 60, 60)
            elif severity == 'MEDIUM':
                self.set_text_color(234, 179, 8)
            else:
                self.set_text_color(100, 100, 100)
            if row_fill:
                self.set_fill_color(245, 245, 255)
            else:
                self.set_fill_color(255, 255, 255)
            self.set_font('Helvetica', 'B', 8)
            self.cell(col_widths[0], 6, severity, border=1, fill=True)
            self.set_font('Helvetica', '', 8)
            self.set_text_color(50, 50, 50)
            # Remove any special unicode chars so fpdf won't crash since we only have Helvetica
            title_text = str(f.get('title', '')[:35]).encode('ascii', 'ignore').decode()
            desc_text = str(f.get('description', '')[:40]).encode('ascii', 'ignore').decode()
            self.cell(col_widths[1], 6, title_text, border=1, fill=True)
            self.cell(col_widths[2], 6, desc_text, border=1, fill=True)
            self.ln()
            row_fill = not row_fill
        self.ln(4)


def generate_audit_pdf(
    address: str,
    chain: str,
    result: dict,
    contract: dict = None,
) -> bytes:
    """
    Generate a professional Aegis security audit PDF report.
    Returns the PDF as bytes suitable for Telegram send_document.
    """
    pdf = AegisPDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    score = result.get('risk_score', 0) or 0
    rec = result.get('recommendation', 'CAUTION')
    summary = result.get('summary', 'No summary available.')
    # remove special chars to avoid Helvetica issue
    summary = str(summary).encode('ascii', 'ignore').decode()

    token_name = (contract or {}).get('token_name', '') or address[:10] + '...'
    token_name = str(token_name).encode('ascii', 'ignore').decode()

    # ── Title block ────────────────────────────────────────────────
    pdf.ln(5)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC'), align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # ── Contract info ──────────────────────────────────────────────
    pdf.write_section_title('CONTRACT INFORMATION')
    pdf.write_key_value('Address', address)
    chain_names = {
        'eth': 'Ethereum (ETH)', 'bsc': 'BNB Smart Chain (BSC)',
        'polygon': 'Polygon (MATIC)', 'arb': 'Arbitrum One',
        'base': 'Base', 'op': 'Optimism', 'solana': 'Solana'
    }
    pdf.write_key_value('Chain', chain_names.get(chain, chain.upper()))
    pdf.write_key_value('Token', token_name)
    if contract and contract.get('verified'):
        pdf.write_key_value('Verified', 'Yes')
    pdf.ln(4)

    # ── Risk score ─────────────────────────────────────────────────
    pdf.write_section_title('RISK ASSESSMENT')
    try:
        score_val = float(score)
    except:
        score_val = 0.0
    pdf.write_risk_bar(score_val)
    pdf.set_font('Helvetica', 'B', 14)
    if score_val >= 7:
        pdf.set_text_color(220, 38, 38)
    elif score_val >= 4:
        pdf.set_text_color(234, 179, 8)
    else:
        pdf.set_text_color(22, 163, 74)
    pdf.cell(0, 10, f'VERDICT: {rec}', align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Executive summary ──────────────────────────────────────────
    pdf.write_section_title('EXECUTIVE SUMMARY')
    pdf.write_body(summary)

    # ── Findings table ─────────────────────────────────────────────
    consensus = result.get('consensus_findings', [])
    single = result.get('single_tool_findings', result.get('single_source_findings', []))
    all_findings = consensus + single
    pdf.write_findings_table(all_findings, 'DETAILED FINDINGS')

    # ── Security flags ─────────────────────────────────────────────
    pdf.write_section_title('SECURITY FLAGS')
    flags = [
        ('Honeypot', result.get('honeypot', False), True),
        ('Mint Function', result.get('mint_function', False), True),
        ('Owner Renounced', result.get('owner_renounced', False), False),
        ('Hidden Owner', result.get('hidden_owner', False), True),
        ('Blacklist Function', result.get('blacklist_function', False), True),
        ('Transfer Tax Modifiable', result.get('transfer_tax_modifiable', False), True),
        ('Proxy Pattern', result.get('proxy_pattern', False), True),
        ('Liquidity Concerns', result.get('liquidity_concerns', False), True),
    ]
    for label, val, danger in flags:
        if danger and val:
            pdf.set_text_color(220, 38, 38)
            status = ' YES'
        elif danger and not val:
            pdf.set_text_color(22, 163, 74)
            status = ' NO'
        elif not danger and val:
            pdf.set_text_color(22, 163, 74)
            status = ' YES'
        else:
            pdf.set_text_color(100, 100, 100)
            status = '-'
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(60, 6, f'{label}:', align='R')
        pdf.set_font('Helvetica', '', 10)
        pdf.cell(0, 6, status, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Positive signals ───────────────────────────────────────────
    positives = result.get('positive_signals', [])
    if positives:
        pdf.write_section_title('POSITIVE SIGNALS')
        for p in positives:
            p_ascii = str(p).encode('ascii', 'ignore').decode()
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(22, 163, 74)
            pdf.cell(0, 6, f'   {p_ascii}', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # ── Disclaimer ────────────────────────────────────────────────
    pdf.set_font('Helvetica', 'I', 7)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4,
        'DISCLAIMER: This report is generated by an automated security analysis engine '
        'and does not constitute professional financial or investment advice. '
        'Always conduct your own research before interacting with any smart contract.',
        align='C'
    )

    return bytes(pdf.output())


async def send_pdf_report(update, context, address: str, chain: str, result: dict, contract: dict = None):
    """Generate PDF and send it as a Telegram document."""
    msg = await update.message.reply_text("📄 Generating professional PDF report...")
    try:
        pdf_bytes = generate_audit_pdf(address, chain, result, contract)
        pdf_file = io.BytesIO(pdf_bytes)
        pdf_file.name = f"Aegis_Audit_{address[:10]}_{chain}.pdf"

        await context.bot.send_document(
            chat_id=update.effective_chat.id,
            document=pdf_file,
            caption=f"🛡 Aegis Security Audit Report\n{address}\nChain: {chain.upper()}",
            filename=pdf_file.name,
        )
        await msg.delete()
    except Exception as e:
        await msg.edit_text(f"❌ Failed to generate PDF: {html.escape(str(e))}")
